//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace miForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orden", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class Orden : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CajxPalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroLoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodCentroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodRecursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DuracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpImpresoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecursoLoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoPalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UmEtiquetaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CajxPal {
            get {
                return this.CajxPalField;
            }
            set {
                if ((this.CajxPalField.Equals(value) != true)) {
                    this.CajxPalField = value;
                    this.RaisePropertyChanged("CajxPal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroLote {
            get {
                return this.CentroLoteField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroLoteField, value) != true)) {
                    this.CentroLoteField = value;
                    this.RaisePropertyChanged("CentroLote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCentro {
            get {
                return this.CodCentroField;
            }
            set {
                if ((object.ReferenceEquals(this.CodCentroField, value) != true)) {
                    this.CodCentroField = value;
                    this.RaisePropertyChanged("CodCentro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodOrden {
            get {
                return this.CodOrdenField;
            }
            set {
                if ((object.ReferenceEquals(this.CodOrdenField, value) != true)) {
                    this.CodOrdenField = value;
                    this.RaisePropertyChanged("CodOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodProducto {
            get {
                return this.CodProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodProductoField, value) != true)) {
                    this.CodProductoField = value;
                    this.RaisePropertyChanged("CodProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodRecurso {
            get {
                return this.CodRecursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodRecursoField, value) != true)) {
                    this.CodRecursoField = value;
                    this.RaisePropertyChanged("CodRecurso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duracion {
            get {
                return this.DuracionField;
            }
            set {
                if ((this.DuracionField.Equals(value) != true)) {
                    this.DuracionField = value;
                    this.RaisePropertyChanged("Duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpImpresora {
            get {
                return this.IpImpresoraField;
            }
            set {
                if ((object.ReferenceEquals(this.IpImpresoraField, value) != true)) {
                    this.IpImpresoraField = value;
                    this.RaisePropertyChanged("IpImpresora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecursoLote {
            get {
                return this.RecursoLoteField;
            }
            set {
                if ((object.ReferenceEquals(this.RecursoLoteField, value) != true)) {
                    this.RecursoLoteField = value;
                    this.RaisePropertyChanged("RecursoLote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoPal {
            get {
                return this.TipoPalField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoPalField, value) != true)) {
                    this.TipoPalField = value;
                    this.RaisePropertyChanged("TipoPal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UmEtiqueta {
            get {
                return this.UmEtiquetaField;
            }
            set {
                if ((object.ReferenceEquals(this.UmEtiquetaField, value) != true)) {
                    this.UmEtiquetaField = value;
                    this.RaisePropertyChanged("UmEtiqueta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unidad {
            get {
                return this.UnidadField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadField, value) != true)) {
                    this.UnidadField = value;
                    this.RaisePropertyChanged("Unidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData2", ReplyAction="http://tempuri.org/IService1/GetData2Response")]
        string GetData2(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData2", ReplyAction="http://tempuri.org/IService1/GetData2Response")]
        System.Threading.Tasks.Task<string> GetData2Async(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrden", ReplyAction="http://tempuri.org/IService1/GetOrdenResponse")]
        miForm.ServiceReference1.Orden GetOrden();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrden", ReplyAction="http://tempuri.org/IService1/GetOrdenResponse")]
        System.Threading.Tasks.Task<miForm.ServiceReference1.Orden> GetOrdenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrden2", ReplyAction="http://tempuri.org/IService1/GetOrden2Response")]
        string[][] GetOrden2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrden2", ReplyAction="http://tempuri.org/IService1/GetOrden2Response")]
        System.Threading.Tasks.Task<string[][]> GetOrden2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        miForm.ServiceReference1.CompositeType GetDataUsingDataContract(miForm.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<miForm.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(miForm.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : miForm.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<miForm.ServiceReference1.IService1>, miForm.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public string GetData2(int value) {
            return base.Channel.GetData2(value);
        }
        
        public System.Threading.Tasks.Task<string> GetData2Async(int value) {
            return base.Channel.GetData2Async(value);
        }
        
        public miForm.ServiceReference1.Orden GetOrden() {
            return base.Channel.GetOrden();
        }
        
        public System.Threading.Tasks.Task<miForm.ServiceReference1.Orden> GetOrdenAsync() {
            return base.Channel.GetOrdenAsync();
        }
        
        public string[][] GetOrden2() {
            return base.Channel.GetOrden2();
        }
        
        public System.Threading.Tasks.Task<string[][]> GetOrden2Async() {
            return base.Channel.GetOrden2Async();
        }
        
        public miForm.ServiceReference1.CompositeType GetDataUsingDataContract(miForm.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<miForm.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(miForm.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
